In [2]:
import pandas as pd
import numpy as np
#from vadetisweb.anomaly_algorithms.detection import helper_functions
from vadetisweb.anomaly_algorithms import *

In [3]:
X_1 = [4, 2, 2, 5, 9, 8, 3]
X_2 = [10, 5, 4, 2, 6, 8, 9]
X_3 = [6, 4, 10, 3, 1, 2, 8]

df = pd.DataFrame({1 : X_1, 2: X_2, 3:X_3})
print(df)

   1   2   3
0  4  10   6
1  2   5   4
2  2   4  10
3  5   2   3
4  9   6   1
5  8   8   2
6  3   9   8


In [3]:
df_mean = df_copy_with_mean(df)
print(df_mean)

   1   2   3      mean
0  4  10   6  6.666667
1  2   5   4  3.666667
2  2   4  10  5.333333
3  5   2   3  3.333333
4  9   6   1  5.333333
5  8   8   2  6.000000
6  3   9   8  6.666667


In [4]:
df_part = df.loc[4]
print(df_part)
std_deviation_i = df_part.loc[[1,2,3]].std(skipna=True, level=None, ddof=0)
print(std_deviation_i)

1    9
2    6
3    1
Name: 4, dtype: int64
3.2998316455372216


In [5]:
df_correlation = pearson(df, 2, window_size=4)
print(df_correlation)

          1         3
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3 -0.016323  0.166097
4  0.323669 -0.226779
5  0.653197 -0.379473
6 -0.048877  0.432904


In [6]:
X_1_part = [2, 2, 5, 9]
X_2_part = [5, 4, 2, 6]
X_3_part = [4, 10, 3, 1]

In [11]:
path = dtw(np.array(X_2_part), np.array(X_1_part), distance='euclidean')
print(path)

[[3. 3. 0. 4.]
 [2. 2. 1. 5.]
 [0. 0. 3. 7.]
 [4. 4. 1. 3.]]
[[ 0. inf inf inf inf]
 [inf  3.  6.  6. 10.]
 [inf  5.  5.  6. 11.]
 [inf  5.  5.  8. 13.]
 [inf  9.  9.  6.  9.]]
(array([0, 1, 2, 3, 3]), array([0, 0, 1, 2, 3]))


In [13]:
path = dtw(np.array(X_2_part), np.array(X_3_part), distance='euclidean')
print(path)

[[1. 5. 2. 4.]
 [0. 6. 1. 3.]
 [2. 8. 1. 1.]
 [2. 4. 3. 5.]]
[[ 0. inf inf inf inf]
 [inf  1.  6.  8. 12.]
 [inf  1.  7.  7. 10.]
 [inf  3.  9.  8.  8.]
 [inf  5.  7. 10. 13.]]
(array([0, 1, 2, 3]), array([0, 1, 2, 3]))


In [4]:
df = df.set_index(pd.date_range('2012-01-01', periods=7))
print(df)

            1   2   3
2012-01-01  4  10   6
2012-01-02  2   5   4
2012-01-03  2   4  10
2012-01-04  5   2   3
2012-01-05  9   6   1
2012-01-06  8   8   2
2012-01-07  3   9   8


In [5]:
df_mean = df_copy_with_mean(df)
print(df_mean)

            1   2   3      mean
2012-01-01  4  10   6  6.666667
2012-01-02  2   5   4  3.666667
2012-01-03  2   4  10  5.333333
2012-01-04  5   2   3  3.333333
2012-01-05  9   6   1  5.333333
2012-01-06  8   8   2  6.000000
2012-01-07  3   9   8  6.666667


In [6]:
df_correlation = dtw_pearson(df, 2, 'euclidean', window_size=4)
print(df_correlation)

[[6. 8. 8. 5.]
 [1. 3. 3. 0.]
 [0. 2. 2. 1.]
 [2. 0. 0. 3.]]
[[ 0. inf inf inf inf]
 [inf  6. 14. 22. 27.]
 [inf  7.  9. 12. 12.]
 [inf  7.  9. 11. 12.]
 [inf  9.  7.  7. 10.]]
[[4. 6. 0. 7.]
 [1. 1. 5. 2.]
 [2. 0. 6. 1.]
 [4. 2. 8. 1.]]
[[ 0. inf inf inf inf]
 [inf  4. 10. 10. 17.]
 [inf  5.  5. 10. 12.]
 [inf  7.  5. 11. 11.]
 [inf 11.  7. 13. 12.]]
[[3. 3. 0. 4.]
 [2. 2. 1. 5.]
 [0. 0. 3. 7.]
 [4. 4. 1. 3.]]
[[ 0. inf inf inf inf]
 [inf  3.  6.  6. 10.]
 [inf  5.  5.  6. 11.]
 [inf  5.  5.  8. 13.]
 [inf  9.  9.  6.  9.]]
[[1. 5. 2. 4.]
 [0. 6. 1. 3.]
 [2. 8. 1. 1.]
 [2. 4. 3. 5.]]
[[ 0. inf inf inf inf]
 [inf  1.  6.  8. 12.]
 [inf  1.  7.  7. 10.]
 [inf  3.  9.  8.  8.]
 [inf  5.  7. 10. 13.]]
[[2. 1. 5. 4.]
 [0. 3. 7. 6.]
 [4. 1. 3. 2.]
 [6. 3. 1. 0.]]
[[ 0. inf inf inf inf]
 [inf  2.  3.  8. 12.]
 [inf  2.  5. 10. 14.]
 [inf  6.  3.  6.  8.]
 [inf 12.  6.  4.  4.]]
[[6. 1. 3. 2.]
 [8. 1. 1. 0.]
 [4. 3. 5. 4.]
 [2. 5. 7. 6.]]
[[ 0. inf inf inf inf]
 [inf  6.  7. 10. 12.]
 [inf 14

In [7]:
df_results = df_lisa_time_series(2, df_mean, df_correlation)
print(df_results)

                   2
2012-01-01       NaN
2012-01-02       NaN
2012-01-03       NaN
2012-01-04 -0.437750
2012-01-05  0.212509
2012-01-06  0.854271
2012-01-07  0.196510


In [16]:
df = df.set_index(pd.date_range('2012-01-01', periods=7))
print(df)
df_mean = df_copy_with_mean(df)
df_correlation = dtw_pearson(df, 2, 'euclidean', window_size=4)
df_results = df_lisa_time_series(2, df_mean, df_correlation)
print(df_results)

            1   2   3
2012-01-01  4  10   6
2012-01-02  2   5   4
2012-01-03  2   4  10
2012-01-04  5   2   3
2012-01-05  9   6   1
2012-01-06  8   8   2
2012-01-07  3   9   8
[[6. 8. 8. 5.]
 [1. 3. 3. 0.]
 [0. 2. 2. 1.]
 [2. 0. 0. 3.]]
[[ 0. inf inf inf inf]
 [inf  6. 14. 22. 27.]
 [inf  7.  9. 12. 12.]
 [inf  7.  9. 11. 12.]
 [inf  9.  7.  7. 10.]]
[[4. 6. 0. 7.]
 [1. 1. 5. 2.]
 [2. 0. 6. 1.]
 [4. 2. 8. 1.]]
[[ 0. inf inf inf inf]
 [inf  4. 10. 10. 17.]
 [inf  5.  5. 10. 12.]
 [inf  7.  5. 11. 11.]
 [inf 11.  7. 13. 12.]]
[[3. 3. 0. 4.]
 [2. 2. 1. 5.]
 [0. 0. 3. 7.]
 [4. 4. 1. 3.]]
[[ 0. inf inf inf inf]
 [inf  3.  6.  6. 10.]
 [inf  5.  5.  6. 11.]
 [inf  5.  5.  8. 13.]
 [inf  9.  9.  6.  9.]]
[[1. 5. 2. 4.]
 [0. 6. 1. 3.]
 [2. 8. 1. 1.]
 [2. 4. 3. 5.]]
[[ 0. inf inf inf inf]
 [inf  1.  6.  8. 12.]
 [inf  1.  7.  7. 10.]
 [inf  3.  9.  8.  8.]
 [inf  5.  7. 10. 13.]]
[[2. 1. 5. 4.]
 [0. 3. 7. 6.]
 [4. 1. 3. 2.]
 [6. 3. 1. 0.]]
[[ 0. inf inf inf inf]
 [inf  2.  3.  8. 12.]
 [inf  2.